/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var p=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},q="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a},aa=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");
},t=aa(this),u=function(a,b){if(b)a:{var d=t;a=a.split(".");for(var g=0;g<a.length-1;g++){var e=a[g];if(!(e in d))break a;d=d[e]}a=a[a.length-1];g=d[a];b=b(g);b!=g&&null!=b&&q(d,a,{configurable:!0,writable:!0,value:b})}};
u("Symbol",function(a){if(a)return a;var b=function(l,c){this.g=l;q(this,"description",{configurable:!0,writable:!0,value:c})};b.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",g=0,e=function(l){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(d+(l||"")+"_"+g++,l)};return e});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<b.length;d++){var g=t[b[d]];"function"===typeof g&&"function"!=typeof g.prototype[a]&&q(g.prototype,a,{configurable:!0,writable:!0,value:function(){return ba(p(this))}})}return a});
var ba=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},v=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:p(a)}},ca="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},w;
if("function"==typeof Object.setPrototypeOf)w=Object.setPrototypeOf;else{var x;a:{var da={a:!0},y={};try{y.__proto__=da;x=y.a;break a}catch(a){}x=!1}w=x?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var z=w,A=function(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(z)z(a,b);else for(var d in b)if("prototype"!=d)if(Object.defineProperties){var g=Object.getOwnPropertyDescriptor(b,d);g&&Object.defineProperty(a,d,g)}else a[d]=b[d];a.na=b.prototype};
u("Promise",function(a){function b(){this.g=null}function d(c){return c instanceof e?c:new e(function(f){f(c)})}if(a)return a;b.prototype.i=function(c){if(null==this.g){this.g=[];var f=this;this.j(function(){f.s()})}this.g.push(c)};var g=t.setTimeout;b.prototype.j=function(c){g(c,0)};b.prototype.s=function(){for(;this.g&&this.g.length;){var c=this.g;this.g=[];for(var f=0;f<c.length;++f){var h=c[f];c[f]=null;try{h()}catch(k){this.o(k)}}}this.g=null};b.prototype.o=function(c){this.j(function(){throw c;
})};var e=function(c){this.i=0;this.j=void 0;this.g=[];this.O=!1;var f=this.o();try{c(f.resolve,f.reject)}catch(h){f.reject(h)}};e.prototype.o=function(){function c(k){return function(m){h||(h=!0,k.call(f,m))}}var f=this,h=!1;return{resolve:c(this.W),reject:c(this.s)}};e.prototype.W=function(c){if(c===this)this.s(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof e)this.ka(c);else{a:switch(typeof c){case "object":var f=null!=c;break a;case "function":f=!0;break a;default:f=
!1}f?this.V(c):this.N(c)}};e.prototype.V=function(c){var f=void 0;try{f=c.then}catch(h){this.s(h);return}"function"==typeof f?this.ma(f,c):this.N(c)};e.prototype.s=function(c){this.H(2,c)};e.prototype.N=function(c){this.H(1,c)};e.prototype.H=function(c,f){if(0!=this.i)throw Error("Cannot settle("+c+", "+f+"): Promise already settled in state"+this.i);this.i=c;this.j=f;2===this.i&&this.ha();this.T()};e.prototype.ha=function(){var c=this;g(function(){if(c.U()){var f=t.console;"undefined"!==typeof f&&
f.error(c.j)}},1)};e.prototype.U=function(){if(this.O)return!1;var c=t.CustomEvent,f=t.Event,h=t.dispatchEvent;if("undefined"===typeof h)return!0;"function"===typeof c?c=new c("unhandledrejection",{cancelable:!0}):"function"===typeof f?c=new f("unhandledrejection",{cancelable:!0}):(c=t.document.createEvent("CustomEvent"),c.initCustomEvent("unhandledrejection",!1,!0,c));c.promise=this;c.reason=this.j;return h(c)};e.prototype.T=function(){if(null!=this.g){for(var c=0;c<this.g.length;++c)l.i(this.g[c]);
this.g=null}};var l=new b;e.prototype.ka=function(c){var f=this.o();c.u(f.resolve,f.reject)};e.prototype.ma=function(c,f){var h=this.o();try{c.call(f,h.resolve,h.reject)}catch(k){h.reject(k)}};e.prototype.then=function(c,f){function h(n,r){return"function"==typeof n?function(G){try{k(n(G))}catch(H){m(H)}}:r}var k,m,I=new e(function(n,r){k=n;m=r});this.u(h(c,k),h(f,m));return I};e.prototype.catch=function(c){return this.then(void 0,c)};e.prototype.u=function(c,f){function h(){switch(k.i){case 1:c(k.j);
break;case 2:f(k.j);break;default:throw Error("Unexpected state: "+k.i);}}var k=this;null==this.g?l.i(h):this.g.push(h);this.O=!0};e.resolve=d;e.reject=function(c){return new e(function(f,h){h(c)})};e.race=function(c){return new e(function(f,h){for(var k=v(c),m=k.next();!m.done;m=k.next())d(m.value).u(f,h)})};e.all=function(c){var f=v(c),h=f.next();return h.done?d([]):new e(function(k,m){function I(G){return function(H){n[G]=H;r--;0==r&&k(n)}}var n=[],r=0;do n.push(void 0),r++,d(h.value).u(I(n.length-
1),m),h=f.next();while(!h.done)})};return e});var ea=function(a,b){a instanceof String&&(a+="");var d=0,g=!1,e={next:function(){if(!g&&d<a.length){var l=d++;return{value:b(l,a[l]),done:!1}}g=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};u("Array.prototype.entries",function(a){return a?a:function(){return ea(this,function(b,d){return[b,d]})}});
var B=this||self,C=function(a,b){function d(){}d.prototype=b.prototype;a.na=b.prototype;a.prototype=new d;a.prototype.constructor=a;a.oa=function(g,e,l){for(var c=Array(arguments.length-2),f=2;f<arguments.length;f++)c[f-2]=arguments[f];return b.prototype[e].apply(g,c)}},D=function(a){return a};var E=function(a){this.g=a};function F(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,F);else{var d=Error().stack;d&&(this.stack=d)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}C(F,Error);F.prototype.name="CustomError";function J(a,b){a=a.split("%s");for(var d="",g=a.length-1,e=0;e<g;e++)d+=a[e]+(e<b.length?b[e]:"%s");F.call(this,d+a[g])}C(J,F);J.prototype.name="AssertionError";var K=function(a,b,d){if(!a){var g="Assertion failed";if(b){g+=": "+b;var e=Array.prototype.slice.call(arguments,2)}throw new J(""+g,e||[]);}},L=function(a,b){throw new J("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var M=function(a,b){this.g=a;this.i=b||null};A(M,E);M.prototype.then=function(a,b,d){var g;a&&(g=fa(this,a));this.g.aa(g,b,d)};var fa=function(a,b){var d=a.i;return d?function(g){b.call(this,new d(g))}:b};var ha=[];var N=function(a){this.g=a||gbar.a;this.i=null};A(N,E);var ia=function(){K(!Object.isSealed(N),"Cannot use getInstance() with a sealed constructor.");var a="v";if(N.v&&N.hasOwnProperty(a))a=N.v;else{ha.push(N);var b=new N;N.v=b;K(N.hasOwnProperty(a),"Could not instantiate singleton.");a=b}a.i||(a.i=new M(a.g.bh()));return a.i};var O=function(a,b){this.name=a;this.value=b};O.prototype.toString=function(){return this.name};
var P=new O("OFF",Infinity),Q=new O("WARNING",900),ja=new O("CONFIG",700),ka=function(){},la,ma=function(){},na=function(a,b){this.g=null;this.o=[];this.i=(void 0===b?null:b)||null;this.j=[];this.s={g:function(){return a}}},oa=function(a){if(a.g)return a.g;if(a.i)return oa(a.i);L("Root logger has no level set.");return P},pa=function(a){for(var b=new ma;a;)a.o.forEach(function(d){d(b)}),a=a.i},qa=function(){this.entries={};var a=new na("");a.g=ja;this.entries[""]=a},R,S=function(a,b){var d=a.entries[b];
if(d)return d;d=S(a,b.slice(0,Math.max(b.lastIndexOf("."),0)));var g=new na(b,d);a.entries[b]=g;d.j.push(g);return g},T=function(){R||(R=new qa);return R};/*

 SPDX-License-Identifier: Apache-2.0
*/
var U;var V=function(a,b){this.g=a===ra&&b||"";this.i=sa};V.prototype.toString=function(){return"Const{"+this.g+"}"};var sa={},ra={};var W=function(a,b){this.g=b===ta?a:""};W.prototype.toString=function(){return this.g+""};var ta={};var ua=[],va=function(a){var b;if(b=S(T(),"safevalues").s){a="A URL with content '"+a+"' was sanitized away.";var d;if(d=b)if(d=b&&Q){d=Q.value;var g=b?oa(S(T(),b.g())):P;d=d>=g.value}d&&(b=S(T(),b.g()),"function"===typeof a&&a(),la||(la=new ka),pa(b))}};-1===ua.indexOf(va)&&ua.push(va);function wa(a){var b=new V(ra,"https://apis.google.com/js/client.js");b instanceof V&&b.constructor===V&&b.i===sa?b=b.g:(L("expected object of type Const, got '"+b+"'"),b="type_error:Const");if(void 0===U){var d=null;var g=B.trustedTypes;if(g&&g.createPolicy){try{d=g.createPolicy("goog#html",{createHTML:D,createScript:D,createScriptURL:D})}catch(c){B.console&&B.console.error(c.message)}U=d}else U=d}b=(d=U)?d.createScriptURL(b):b;b=new W(b,ta);b instanceof W&&b.constructor===W?b=b.g:(d=typeof b,L("expected object of type TrustedResourceUrl, got '"+
b+"' of type "+("object"!=d?d:b?Array.isArray(b)?"array":d:"null")),b="type_error:TrustedResourceUrl");a.src=b;var e,l;(e=(b=null==(l=(e=(a.ownerDocument&&a.ownerDocument.defaultView||window).document).querySelector)?void 0:l.call(e,"script[nonce]"))?b.nonce||b.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",e)};var xa=function(){var a=document;var b="SCRIPT";"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)};function ya(){window.performance.mark("gapi_load_end");window.performance.measure("gapi_load","gapi_load_start","gapi_load_end");X()}var X,Y=null,Z=window;
function za(){if(Y)return Y;window.performance.mark("gapi_load_start");var a=Z.colabExperiments&&Z.colabExperiments.first_party_auth;return a&&"undefined"!==typeof gbar?Y=(new Promise(function(b){ia().then(function(){b()})})).then(function(){window.performance.mark("gapi_load_end");window.performance.measure("gapi_load","gapi_load_start","gapi_load_end");return new Promise(function(b){gapi.load("auth:client",b)})}):Y=new Promise(function(b,d){X=b;Z.gapi_onload=function(){a?X():gapi.load("auth:client",
ya)};var g=xa();wa(g);g.async=!0;g.onerror=function(){d(Error("Error loading "+g.src))};b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(g,b)})}Z.colab_gapi_loader={load:za};za().then(function(){},function(){});
